trigger: none
resources:
  repositories:
    - repository: DevOpsTemplates
      name: DigitalPayments/DevOps-Templates
      type: git
      ref: master


stages:
- stage: build
  displayName: "Build RestAPI1.0-SDK"
  jobs:
  - template: pipelines/restapi1.0-java-sdk.yaml@DevOpsTemplates
